SOAL NO. 1

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[50, 67, 32], [27, 67, 45]])
print(X)

[[50 67 32]
 [27 67 45]]


In [3]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[50, 67, 32], [27, 67, 45]])
print(X_pt)

tensor([[50, 67, 32],
        [27, 67, 45]])


In [4]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[50, 67, 32], [27, 67, 45]])
print(X_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[50, 67, 32],
       [27, 67, 45]], dtype=int32)>


SOAL NO. 2

In [5]:
# lakukan transpose pada matrix X, X_pt dan X_tf
X.T

array([[50, 27],
       [67, 67],
       [32, 45]])

In [6]:
X_pt.T

tensor([[50, 27],
        [67, 67],
        [32, 45]])

In [7]:
tf.transpose(X_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[50, 27],
       [67, 67],
       [32, 45]], dtype=int32)>