# Basic Tensor Arithmetic  (The Hadamard Product)

No. 1

In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[34, 56, 23], [12, 35, 63]])
X

array([[34, 56, 23],
       [12, 35, 63]])

In [4]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[40, 12, 53], [23, 87, 34]])
X_pt

tensor([[40, 12, 53],
        [23, 87, 34]])

In [5]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[4, 3, 2], [5, 6, 0]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[4, 3, 2],
       [5, 6, 0]], dtype=int32)>

**Perkalian matrix X, X_pt dan X_tf dengan suatu skalar**

In [6]:
X1 = X * 5
X1

array([[170, 280, 115],
       [ 60, 175, 315]])

In [7]:
X2 = X_pt * 5
X2

tensor([[200,  60, 265],
        [115, 435, 170]])

In [8]:
X3 = X_tf * 5
X3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[20, 15, 10],
       [25, 30,  0]], dtype=int32)>

**penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar**

In [9]:
Xa = X + 10
Xa

array([[44, 66, 33],
       [22, 45, 73]])

In [10]:
Xb = X_pt + 10
Xb

tensor([[50, 22, 63],
        [33, 97, 44]])

In [11]:
Xc = X_tf + 10
Xc

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[14, 13, 12],
       [15, 16, 10]], dtype=int32)>

**Pengurangan matrix X, X_pt dan X_tf dengan suatu skalar**

In [12]:
XA = X - 12
XA

array([[22, 44, 11],
       [ 0, 23, 51]])

In [13]:
XB = X_pt - 12
XB

tensor([[28,  0, 41],
        [11, 75, 22]])

In [14]:
XC = X_tf - 12
XC

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ -8,  -9, -10],
       [ -7,  -6, -12]], dtype=int32)>

No. 2

In [15]:
# buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y = np.array([[2, 4, 8], [1, 0, 2]])
Y

array([[2, 4, 8],
       [1, 0, 2]])

In [16]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = torch.tensor([[4, 7, 9], [4, 7, 2]])
Y_pt

tensor([[4, 7, 9],
        [4, 7, 2]])

In [17]:
# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable([[3, 6, 9], [0, 2, 7]])
Y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[3, 6, 9],
       [0, 2, 7]], dtype=int32)>

In [18]:
# Perkalian matrix X dengan Y
xy = X * Y
xy

array([[ 68, 224, 184],
       [ 12,   0, 126]])

In [19]:
# Perkalian matrix X_pt dengan Y_pt
XpYp = X_pt * Y_pt
XpYp

tensor([[160,  84, 477],
        [ 92, 609,  68]])

In [20]:
# Perkalian matrix X_tf dengan Y_tf
XtYt = X_tf * Y_tf
XtYt

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12, 18, 18],
       [ 0, 12,  0]], dtype=int32)>