No. 1

In [83]:
import numpy as np
import torch as pt
import tensorflow as tf

In [84]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[7, 6, 8], [9, 1, 3]])
print(X)

[[7 6 8]
 [9 1 3]]


In [85]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
print(np.sum(X))

34


In [86]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[7, 6, 8], [9, 1, 3]])
print(X_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[7, 6, 8],
       [9, 1, 3]], dtype=int32)>


In [87]:
# hitung hasil penjumlahan seluruh elemen matrix X

In [88]:
print(np.sum(X))

34


In [89]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt
X_pt = torch.tensor([[7, 6, 8], [9, 1, 3]])
torch.sum(X_pt)

tensor(34)

In [90]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=34>

No. 3

In [91]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
X.sum(axis=1)


array([21, 13])

In [92]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
torch.sum(X_pt, 1)

tensor([21, 13])

In [93]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([21, 13], dtype=int32)>

No. 4

In [94]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
X.sum(axis=0)

array([16,  7, 11])

In [95]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
torch.sum(X_pt, 0)

tensor([16,  7, 11])

In [96]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([16,  7, 11], dtype=int32)>

No. 5

In [97]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf
print(np.min(X))
print(torch.min(X_pt))
print(tf.reduce_min(X_tf))

1
tensor(1)
tf.Tensor(1, shape=(), dtype=int32)


In [98]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf
print(np.max(X))
print(torch.max(X_pt))
print(tf.reduce_max(X_tf))

9
tensor(9)
tf.Tensor(9, shape=(), dtype=int32)


In [99]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf
print(X.mean())
print(X_pt.float().mean())
print(tf.reduce_mean(X_tf))

5.666666666666667
tensor(5.6667)
tf.Tensor(5, shape=(), dtype=int32)


No. 6

In [100]:
# hitung hasil perkalian seluruh elemen matrix X
X.prod()

np.int64(9072)

In [101]:
# hitung hasil perkalian seluruh elemen matrix X_pt
torch.prod(X_pt)

tensor(9072)

In [102]:
# hitung hasil perkalian seluruh elemen matrix X_tf
tf.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=9072>