SOAL NO 1

In [3]:
import numpy as np

In [4]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[10, 20, 30], [40, 50, 60]])
print(X)

[[10 20 30]
 [40 50 60]]


In [5]:
# tampilkan ukuran dari matrix X
print(f"X: {X.shape}")

X: (2, 3)


In [6]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
print(X[:, 0])

[10 40]


In [7]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
print(X[:, 1])

[20 50]


SOAL NO 2

In [ ]:
# ulangi soal nomor 1 menggunakan pytorch

In [8]:
import torch as pt

In [9]:
# buat matrix X berukuran 2x3
X = pt.tensor([[10, 20, 30], [40, 50, 60]])
print(X)

tensor([[10, 20, 30],
        [40, 50, 60]])


In [10]:
# tampilkan ukuran dari matrix X
print(f"X: {X.shape}")

X: torch.Size([2, 3])


In [11]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
print(X[:, 0].tolist())

[10, 40]


In [12]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
print(X[:, 1].tolist())

[20, 50]


In [ ]:
# ulangi soal nomor 1 menggunakan tensorflow

In [14]:
import tensorflow as tf

In [17]:
# buat matrix X berukuran 2x3
X = tf.Variable([[10, 20, 30], [40, 50, 60]])
print(X)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>


In [16]:
# tampilkan ukuran dari matrix X
print(f"X: {X.shape}")

X: (2, 3)


In [18]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
print(X[:, 0].numpy())

[10 40]


In [19]:
# tampilkan seluruh elemen dari kolom kedua dari matrix X
print(X[:, 1].numpy())

[20 50]
