SOAL NO 1

In [ ]:
import numpy as np

In [ ]:
# buat vector x dengan ukuran 3x1
x_np = np.array([[12], [8], [25]])
print(x_np)

[[12]
 [ 8]
 [25]]


In [ ]:
# buat vector y dengan ukuran 3x1
y_np = np.array([[7], [79], [77]])
print(y_np)

[[ 7]
 [79]
 [77]]


In [ ]:
# hitung panjang vector x
len(x_np)

3

In [ ]:
# tampilkan ukuran vector x
x_np.shape

(3, 1)

In [ ]:
# tampilkan tipe data dari vector x
x_np.dtype

dtype('int64')

In [ ]:
# akses elemen pertama dari vector x
x_np[0]

array([12])

In [ ]:
# tampilkan tipe data elemen pertama dari vector x
x_np[0].dtype

dtype('int64')

SOAL NO 2

In [ ]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x_np.T
print(x_t)

[[12  8 25]]


In [ ]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [ ]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y_np.T
print(y_t)

[[ 7 79 77]]


In [ ]:
# tampilkan ukuran dari vector y_t
y_t.shape

(1, 3)

SOAL NO 3

In [ ]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow

PYTORCH

In [ ]:
import torch as pt

In [ ]:
x_pt = pt.tensor([12, 8, 25])
print(x_pt)
x_pt.shape

tensor([12,  8, 25])


torch.Size([3])

In [52]:
x_pT = x_pt.T
print(x_pT)
x_pT.shape

tensor([12,  8, 25])


torch.Size([3])

In [ ]:
y_pt = pt.tensor([7, 79, 77])
print(y_pt)
y_pt.shape

In [ ]:
y_pT = y_pt.T
print(y_pT)
y_pT.shape

TENSORFLOW

In [ ]:
import tensorflow as tf

In [48]:
x_tf = tf.Variable([12, 8, 25], dtype = tf.int32)
print(x_tf)
x_tf.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([12,  8, 25], dtype=int32)>


TensorShape([3])

In [49]:
x_tF = tf.transpose(x_tf)
print(x_tF)
x_tF.shape

tf.Tensor([12  8 25], shape=(3,), dtype=int32)


TensorShape([3])

In [50]:
y_tf = tf.Variable([7, 79, 77], dtype = tf.int32)
print(y_tf)
y_tf.shape

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 7, 79, 77], dtype=int32)>


TensorShape([3])

In [51]:
y_tF = tf.transpose(y_tf)
print(y_tF)
y_tF.shape

tf.Tensor([ 7 79 77], shape=(3,), dtype=int32)


TensorShape([3])