SOAL NO 1. menggunakan numpy, pytorch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm

1. NUMPY

In [2]:
import numpy as np

In [14]:
X = np.array([[4, 1, 2], [7, 3, 5], [9, 8, 6]])
X

array([[4, 1, 2],
       [7, 3, 5],
       [9, 8, 6]])

In [13]:
(4**2 + 1**2 + 2**2 + 7**2 + 3**2 + 5**2 + 9**2 + 8**2 + 6**2)**(1/2)

16.881943016134134

In [5]:
np.linalg.norm(X) #L2 norm

np.float64(14.832396974191326)

2. PYTORCH

In [6]:
import torch

In [18]:
X_pt = torch.tensor([[4, 1, 2], [7, 3, 5], [9, 8, 6.]]) # torch.norm() supports floats only
X_pt

tensor([[4., 1., 2.],
        [7., 3., 5.],
        [9., 8., 6.]])

In [19]:
torch.norm(X_pt)

tensor(16.8819)

3. TENSORFLOW

In [21]:
import tensorflow as tf

In [23]:
X_tf = tf.Variable([[4, 1, 2], [7, 3, 5], [9, 8, 6.]]) # tf.norm() also supports floats only
X_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[4., 1., 2.],
       [7., 3., 5.],
       [9., 8., 6.]], dtype=float32)>

In [24]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=16.881942749023438>