1. buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
2. tampilkan ukuran matrix A dan vector b
3. kalikan matrix A dengan vector b
kalikan matrix A_pt dengan vector b_pt
kalikan matrix A_tf dengan vector b_tf
4. buat matrix B dengan ukuran 3x3 menggunakan numpy
buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
5. kalikan matrix A dengan matrix B
kalikan matrix A_pt dengan matrix B_pt
kalikan matrix A_tf dengan matrix B_tf
6. buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?


In [9]:
import numpy as np
import torch
import tensorflow as tf


1

In [10]:
# membuat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy

A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

b = np.array([[7],
              [8],
              [9]])
b

array([[7],
       [8],
       [9]])

In [11]:
# membuat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytor

A_pt = torch.tensor([[1, 2, 3],
              [4, 5, 6]])
A_pt

b_pt = torch.tensor([[7],
                     [8],
                     [9]])
b_pt

tensor([[7],
        [8],
        [9]])

In [12]:
# membuat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow

A_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])
A_tf

b_tf = tf.Variable([[7],
                    [8],
                    [9]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[7],
       [8],
       [9]], dtype=int32)>

2

In [13]:
# menampilkan ukuran matrix A dan vector b

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7],
              [8],
              [9]])

print("Ukuran matriks A:", A.shape)
print("Ukuran vektor b:", b.shape)

Ukuran matriks A: (2, 3)
Ukuran vektor b: (3, 1)


3

In [14]:
# mengalikan matrix A dengan vector b

A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7],
              [8],
              [9]])
np.dot(A, b)

array([[ 50],
       [122]])

In [15]:
# mengalikan matrix A_pt dengan vector b_pt

import torch

A_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])

b_pt = torch.tensor([[7],
                     [8],
                     [9]])

hasil = torch.matmul(A_pt, b_pt)
print(hasil)

tensor([[ 50],
        [122]])


In [16]:
# mengalikan matrix A_tf dengan vector b_tf

import tensorflow as tf

A_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])

b_tf = tf.Variable([[7],
                    [8],
                    [9]])

hasil = tf.matmul(A_tf, b_tf)
print(hasil)

tf.Tensor(
[[ 50]
 [122]], shape=(2, 1), dtype=int32)


4

In [17]:
# membuat matrix B dengan ukuran 3x3 menggunakan numpy

import numpy as np

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# membuat matrix B_pt dengan ukuran 3x3 menggunakan pytorch

import torch

B_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

B_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
# membuat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow

import tensorflow as tf

B_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

B_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

5

In [20]:
# mengalikan matrix A dengan matrix B

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B


np.dot(A, B)

array([[30, 36, 42],
       [66, 81, 96]])

In [21]:
# mengalikan matrix A_pt dengan matrix B_pt

import torch

A_pt = torch.tensor([[1, 2, 3],
              [4, 5, 6]])
A_pt

B_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
B_pt

hasil = torch.matmul(A_pt, B_pt)
print(hasil)

tensor([[30, 36, 42],
        [66, 81, 96]])


In [22]:
# mengalikan matrix A_tf dengan matrix B_tf

import tensorflow as tf

A_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])
A_tf

B_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
B_tf

hasil = tf.matmul(A_tf, B_tf)
print(hasil)

tf.Tensor(
[[30 36 42]
 [66 81 96]], shape=(2, 3), dtype=int32)


6

In [23]:
# membuktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

print("Hasil perkalian A × B:\n", np.dot(A, B))
try:
    print("Hasil kalikan matrix B dengan matrix A: \n",np.dot(B, A))
except ValueError as e:
    print("\nBA tidak bisa dihitung:")
    print(e)
'''Perkalian matriks tidak bersifat komutatif (AB ≠ BA), karena:
1. Tidak semua pasangan matriks dapat dikalikan dalam kedua urutan (AB bisa tetapi BA tidak, atau sebaliknya)
2. Meskipun kedua perkalian terdefinisi, hasilnya belum tentu sama)'''

Hasil perkalian A × B:
 [[30 36 42]
 [66 81 96]]

BA tidak bisa dihitung:
shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)


'Perkalian matriks tidak bersifat komutatif (AB ≠ BA), karena:\n1. Tidak semua pasangan matriks dapat dikalikan dalam kedua urutan (AB bisa tetapi BA tidak, atau sebaliknya)\n2. Meskipun kedua perkalian terdefinisi, hasilnya belum tentu sama)'