SOAL NO 1. buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris

In [1]:
import numpy as np

In [2]:
# MATRIKS SIMETRIS 3x3
X_sym = np.array([[0, 1, 2], [1, 4, 3], [2, 3, 5]])
X_sym

array([[0, 1, 2],
       [1, 4, 3],
       [2, 3, 5]])

In [5]:
# PEMBUKTIAN
X_sym.T # Matriks simetris ketika ditranspose hasilnya tetap sama

array([[0, 1, 2],
       [1, 4, 3],
       [2, 3, 5]])

In [6]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

SOAL NO 2

Menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4

In [7]:
import torch

In [10]:
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0],  [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

Menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1

In [16]:
b_pt = torch.tensor([5, 3, 7, 9]).reshape(4, 1)
b_pt

tensor([[5],
        [3],
        [7],
        [9]])

Kalikan matrix I dengan vector b_pt

In [17]:
torch.matmul(I, b_pt)

tensor([[5],
        [3],
        [7],
        [9]])